site:
  site_name: "Med.AI.rian"
  name: "Atef Attia 👋"
  role: "Senior ML Engineer"

navigation:
  links:
    - text: "Home"
      url: "/"
    - text: "About"
      url: "/about"
    - text: "Projects"
      url: "/projects"
    - text: "Skills"
      url: "/skills"
    - text: "Articles"
      url: "/articles"
    - text: "Contact"
      url: "/contact"

footer:
  copyright: "Med.AI.rian. All rights reserved."
  links:
    - text: "About"
      url: "/about"
    - text: "Projects"
      url: "/projects"
    - text: "Articles"
      url: "/articles"

contact:
  email: "medairian@gmail.com"
  phone: "+49 157 55088832"
  address: "Munich, Germany"
