site:
  name: "Med.AI.rian"
  description: "Atef Attia 👋 Senior ML Engineer"

navigation:
  links:
    - text: "Home"
      url: "/"
    - text: "About"
      url: "/about"
    - text: "Projects"
      url: "/projects"
    - text: "Skills"
      url: "/skills"
    - text: "Articles"
      url: "/articles"
    - text: "Contact"
      url: "/contact"

footer:
  copyright: "Med.AI.rian. All rights reserved."
  links:
    - text: "Privacy Policy"
      url: "#"
    - text: "Terms of Service"
      url: "#"
    - text: "Blog"
      url: "#"
    - text: "Careers"
      url: "#"

contact:
  email: "contact@medairian.com"
  phone: "+1 (555) 123-4567"
  address: "123 Innovation Drive, Silicon Valley, CA 94025"
